### ISSUE TITLE
ترجمه بعضی کلمات

### ISSUE THREAD

**Issue by eshagh79** [phpbbfarsi/phpBB-Persian-language-3.3.x#6]
سلام
ترجمه بعضی کلمات تو قسمت های مختلف فرق میکنه. برای اینکه ترجمه کامل تر بشه ، بهتره از یک ترجمه استفاده بشه.
چند تا از کلمات رو اینجا میگم ، بنظرتون کدوم ترجمه بهره:
upload = آپلود، بارگذاری
sticky = چسبنده، مهم
topic = موضوع، مبحث
text = متن، نوشته
locked = بسته، قفل
view = مشاهده، بازدید، دیدن
marked = علامت گذاری شده ، علایق، نشانک، نشان شده
all = همه، تمامی

**Comment by meis2m** [comment]
بارگزاری
مهم
موضوع
متن
بسته
بازدید
نشان شده
همه

**Comment by eshagh79** [comment]
بارگزاری به معنی بار کردن و لود کردن هست، منظورتون بارگذاری هست دیگه؟ اگه بله : حله.
sticky = این کلمه رو چسبناک ترجمه کردم چون معنی مهم نمیده و ممکنه در اینده بعضی جا ها باعتث مشکل بشه
locked = این کلمه رو هم قفل ترجمه کردم
marked = اینو هم از علایق به نشان شده و در بعضی جا ها نشانک ترجمه کردم
all = اینو هم از تمامی به همه ترجمه کردم

**Comment by eshagh79** [comment]
بارگزاری به معنی بار کردن و لود کردن هست، منظورتون بارگذاری هست دیگه؟ اگه بله : حله.
sticky = این کلمه رو چسبناک ترجمه کردم چون معنی مهم نمیده و ممکنه در اینده بعضی جا ها باعتث مشکل بشه
locked = این کلمه رو هم قفل ترجمه کردم
marked = اینو هم از علایق به نشان شده و در بعضی جا ها نشانک ترجمه کردم
all = اینو هم از تمامی به همه ترجمه کردم

**Comment by eshagh79** [comment]
بارگزاری به معنی بار کردن و لود کردن هست، منظورتون بارگذاری هست دیگه؟ اگه بله : حله.
sticky = این کلمه رو چسبناک ترجمه کردم چون معنی مهم نمیده و ممکنه در اینده بعضی جا ها باعتث مشکل بشه
locked = این کلمه رو هم قفل ترجمه کردم
marked = اینو هم از علایق به نشان شده و در بعضی جا ها نشانک ترجمه کردم
all = اینو هم از تمامی به همه ترجمه کردم

**Comment by eshagh79** [comment]
بارگزاری به معنی بار کردن و لود کردن هست، منظورتون بارگذاری هست دیگه؟ اگه بله : حله.
sticky = این کلمه رو چسبناک ترجمه کردم چون معنی مهم نمیده و ممکنه در اینده بعضی جا ها باعتث مشکل بشه
locked = این کلمه رو هم قفل ترجمه کردم
marked = اینو هم از علایق به نشان شده و در بعضی جا ها نشانک ترجمه کردم
all = اینو هم از تمامی به همه ترجمه کردم

**Comment by eshagh79** [comment]
بارگزاری به معنی بار کردن و لود کردن هست، منظورتون بارگذاری هست دیگه؟ اگه بله : حله.
sticky = این کلمه رو چسبناک ترجمه کردم چون معنی مهم نمیده و ممکنه در اینده بعضی جا ها باعتث مشکل بشه
locked = این کلمه رو هم قفل ترجمه کردم
marked = اینو هم از علایق به نشان شده و در بعضی جا ها نشانک ترجمه کردم
all = اینو هم از تمامی به همه ترجمه کردم

**Comment by eshagh79** [comment]
بارگزاری به معنی بار کردن و لود کردن هست، منظورتون بارگذاری هست دیگه؟ اگه بله : حله.
sticky = این کلمه رو چسبناک ترجمه کردم چون معنی مهم نمیده و ممکنه در اینده بعضی جا ها باعتث مشکل بشه
locked = این کلمه رو هم قفل ترجمه کردم
marked = اینو هم از علایق به نشان شده و در بعضی جا ها نشانک ترجمه کردم
all = اینو هم از تمامی به همه ترجمه کردم

**Comment by meis2m** [comment]
sticky تحت الفظی به معنای جسبناک معنی میده ولی یک معنیش اینه
همون مهم معنی ما در سیستم انجمن هست
