### ISSUE TITLE
انتشار نسخه جدید

### ISSUE THREAD

**Issue by eshagh79** [phpbbfarsi/phpBB-Persian-language-3.3.x#9]
سلام
بنظرم بهتره یه نسخه جدید از ترجمه رو انتشار بدید چون نسخه قبلی با این نسخه تفاوت زیادی داره و مشکلات زیادی برطرف شده

**Comment by meis2m** [comment]
سلام ، نیازی نیست. صبر میکنیم تا نسخه جدید phpBB
بیاد برای اون منتشر میکنیم.

**Comment by eshagh79** [comment]
مگه انتشار یک نسخه جدید از ترجمه باعث مشکل میشه؟
شاید یکی خواست تازه phpBB نصب کنه ،مجبوره از ترجمه قبلی که کلی تفاوت با این نسخه داره استفاده کنه؟
شاید انتشار جدید phpbb تا سال بعد نیاد یا اصلا اونایی که انجمن دارن نخوان انجمن خودشون رو به نسخه جدید اپدیت کن 
یعنی اگه انجمنشون رو اپدیت نکنن نباید از ترجمه بروز شده استفاده کنن؟

شاید اپدیت phpbbبا این ترجمه سازگار نباشه و کلمات جدیدی بهش اضافه یا کم بشن اونوقت چی .
بازم برای این نسخه اپدیت نمیدین؟

فکر نمیکنم انتشار یه نسخه جدید بیشتر از یک دقیقه وقتتون رو بگیره

**Comment by meis2m** [comment]
برای انتشار نسخه رسمی که مورد تایید سایت مرجع هم باشه معمولا یک ماه طول میکشه 
و ضمن اینکه باید نسخه جدید رو هم وارد سیستم نرم افزاری تست اونا هم کنم و مشکلی نداشته باشه

که معمولا یک ماه قبل از انتشار برای ما میفرستن.

نسخه رسمی نمیتونیم بدیم ولی تو سایت فارسی میشه نسخه اصلاح شده رو بذاریم
